# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-12 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imageFile', models.ImageField(null=True, upload_to='images')),
                ('interest', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='specie',
            name='photoPath',
        ),
        migrations.AddField(
            model_name='specie',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='specie',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='specie',
            name='scientificName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='taxonomic_classification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Category'),
        ),
    ]
